data:
  data_dir: ./data/data/
  hypertuning_subjects_ids:
  - s001
  - s004
  - s005
  - s007
  - s009
  - s010
  - s011
  preprocessing: fft_filtering
  train_split: 0.8
  train_subsample: 1.0
  validation_id_epoch_tuning: s002
loss:
  alpha: 0.7000861097481297
  gamma: 2.0592930645285823
model:
  fully_connected: true
  gat_heads: 1
  gat_hidden_dim: 61
  input_dim: 354
  name: gat
  output_dim: 1
seed: 42
training:
  batch_size: 32
  best_epoch: 25
  best_model_path: ./results/epoch_25.pth
  best_val_score: 0.7094902634961537
  epochs: 3
  lr: 0.0010376376659203812
  max_epochs: 30
  n_trials: 5
