data:
  data_dir: ./data/data/
  hypertuning_subjects_ids:
  - s001
  - s004
  - s005
  - s007
  - s009
  - s010
  - s011
  preprocessing: downsample
  train_split: 0.8
  train_subsample: 1.0
  validation_id_epoch_tuning: s002
loss:
  alpha: 0.7014347393825239
  gamma: 1.1259510602778948
model:
  fully_connected: true
  gat_heads: 4
  gat_hidden_dim: 16
  input_dim: 1
  lstm_hidden_dim: 65
  lstm_layers: 6
  lstm_pth_path: ./results/lstm_epoch_5.pth
  name: lstm_freeze_gat
  output_dim: 1
seed: 42
training:
  batch_size: 32
  best_model_path: ./results/trained_model.pth
  epochs: 5
  lr: 9.285654053922501e-05
  max_epochs: 40
  n_trials: 20
