data:
  data_dir: ./data/data/
  hypertuning_subjects_ids:
  - s001
  - s004
  - s005
  - s007
  - s009
  - s010
  - s011
  preprocessing: acf
  train_split: 0.8
  train_subsample: 1.0
  validation_id_epoch_tuning: s002
loss:
  alpha: 0.7124774623723822
  gamma: 4.484745262195903
model:
  fully_connected: false
  gat_heads: 4
  gat_hidden_dim: 29
  input_dim: 101
  name: gat
  output_dim: 1
seed: 42
training:
  batch_size: 32
  best_epoch: 10
  best_model_path: ./results/epoch_25.pth
  best_val_score: 0.6731210569375478
  epochs: 3
  lr: 9.187969854587162e-05
  max_epochs: 30
  n_trials: 5
