data:
  data_dir: ./data/data/
  hypertuning_subjects_ids:
  - s001
  - s004
  - s005
  - s007
  - s009
  - s010
  - s011
  preprocessing: normalize
  train_split: 0.8
  train_subsample: 1.0
  validation_id_epoch_tuning: s002
loss:
  alpha: 0.75
  gamma: 2.0
model:
  embed_dim: 64
  input_dim: 1
  name: transformer_encoder
  nhead: 4
  num_layers: 2
  output_dim: 1
  patch_size: 10
seed: 42
training:
  batch_size: 32
  best_epoch: 15
  best_model_path: ./results/trained_model.pth
  best_val_score: 0.6408109109704349
  epochs: 5
  lr: 5.0e-05
  max_epochs: 30
  n_trials: 5
