data:
  ar_model: true
  data_dir: ./data/data/
  hypertuning_subjects_ids:
  - s001
  - s004
  - s005
  - s007
  - s009
  - s010
  - s011
  lag: 20
  preprocessing: downsample
  train_split: 0.8
  train_subsample: 1.0
  validation_id_epoch_tuning: s002
loss:
  alpha: 0.75
  gamma: 2.0
model:
  input_dim: 1
  lstm_hidden_dim: 32
  lstm_layers: 1
  name: lstm
  output_dim: 1
seed: 42
training:
  batch_size: 32
  best_epoch: 10
  best_model_path: ./results/trained_model.pth
  best_val_score: 0.4817496690206775
  epochs: 5
  lr: 0.001
  max_epochs: 30
  n_trials: 5
