seed: 42

data:
  data_dir: "./data/data/"
  train_split: 0.8
  train_subsample: 0.1


model:
  input_dim: 1
  lstm_hidden_dim: 32
  gat_hidden_dim: 64
  output_dim: 1
  gat_heads: 8

training:
  batch_size: 32
  lr: 0.001
  epochs: 50
  patience: 10
  checkpoint_path: "./checkpoints/lstm_gat.pth"
  best_model_path: "./checkpoints/best_lstm_gat.pth"

loss:
  alpha: 0.75
  gamma: 2.0
