seed: 42

data:
  data_dir: "./data/data/"
  train_split: 0.8
  train_subsample: 1.0


model:
  input_dim: 1
  lstm_hidden_dim: 32
  gat_hidden_dim: 64
  output_dim: 1
  gat_heads: 8
  lstm_layers: 1
  fully_connected: True

training:
  batch_size: 32
  lr: 0.001
  epochs: 5
  best_model_path: "./results"

loss:
  alpha: 0.75
  gamma: 2.0
